//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.629.0 using the following command:
// xscgen "C:\SteamLibrary\steamapps\common\Farming Simulator 22\shared\xml\schema\fillTypes.xsd" -n =FarmSimulatorFillType
namespace FarmSimulator22Integrations.Parsers
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SoundManager_sound", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoundManager_Sound
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SoundManager_SoundVolume> _volume;
        
        [System.Xml.Serialization.XmlElementAttribute("volume", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<SoundManager_SoundVolume> Volume
        {
            get
            {
                return this._volume;
            }
            private set
            {
                this._volume = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Volume collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VolumeSpecified
        {
            get
            {
                return (this.Volume.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SoundManager_Sound" /> class.</para>
        /// </summary>
        public SoundManager_Sound()
        {
            this._volume = new System.Collections.ObjectModel.Collection<SoundManager_SoundVolume>();
            this._pitch = new System.Collections.ObjectModel.Collection<SoundManager_SoundPitch>();
            this._lowpassGain = new System.Collections.ObjectModel.Collection<SoundManager_SoundLowpassGain>();
            this._lowpassCutoffFrequency = new System.Collections.ObjectModel.Collection<SoundManager_SoundLowpassCutoffFrequency>();
            this._lowpassResonance = new System.Collections.ObjectModel.Collection<SoundManager_SoundLowpassResonance>();
            this._randomization = new System.Collections.ObjectModel.Collection<SoundManager_SoundRandomization>();
            this._sourceRandomization = new System.Collections.ObjectModel.Collection<SoundManager_SoundSourceRandomization>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SoundManager_SoundPitch> _pitch;
        
        [System.Xml.Serialization.XmlElementAttribute("pitch", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<SoundManager_SoundPitch> Pitch
        {
            get
            {
                return this._pitch;
            }
            private set
            {
                this._pitch = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Pitch collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PitchSpecified
        {
            get
            {
                return (this.Pitch.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SoundManager_SoundLowpassGain> _lowpassGain;
        
        [System.Xml.Serialization.XmlElementAttribute("lowpassGain", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<SoundManager_SoundLowpassGain> LowpassGain
        {
            get
            {
                return this._lowpassGain;
            }
            private set
            {
                this._lowpassGain = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the LowpassGain collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LowpassGainSpecified
        {
            get
            {
                return (this.LowpassGain.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SoundManager_SoundLowpassCutoffFrequency> _lowpassCutoffFrequency;
        
        [System.Xml.Serialization.XmlElementAttribute("lowpassCutoffFrequency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<SoundManager_SoundLowpassCutoffFrequency> LowpassCutoffFrequency
        {
            get
            {
                return this._lowpassCutoffFrequency;
            }
            private set
            {
                this._lowpassCutoffFrequency = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the LowpassCutoffFrequency collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LowpassCutoffFrequencySpecified
        {
            get
            {
                return (this.LowpassCutoffFrequency.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SoundManager_SoundLowpassResonance> _lowpassResonance;
        
        [System.Xml.Serialization.XmlElementAttribute("lowpassResonance", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<SoundManager_SoundLowpassResonance> LowpassResonance
        {
            get
            {
                return this._lowpassResonance;
            }
            private set
            {
                this._lowpassResonance = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the LowpassResonance collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LowpassResonanceSpecified
        {
            get
            {
                return (this.LowpassResonance.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SoundManager_SoundRandomization> _randomization;
        
        [System.Xml.Serialization.XmlElementAttribute("randomization", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<SoundManager_SoundRandomization> Randomization
        {
            get
            {
                return this._randomization;
            }
            private set
            {
                this._randomization = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Randomization collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RandomizationSpecified
        {
            get
            {
                return (this.Randomization.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SoundManager_SoundSourceRandomization> _sourceRandomization;
        
        [System.Xml.Serialization.XmlElementAttribute("sourceRandomization", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<SoundManager_SoundSourceRandomization> SourceRandomization
        {
            get
            {
                return this._sourceRandomization;
            }
            private set
            {
                this._sourceRandomization = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the SourceRandomization collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SourceRandomizationSpecified
        {
            get
            {
                return (this.SourceRandomization.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("linkNode")]
        public string LinkNode { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("template")]
        public string Template { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("parent")]
        public string Parent { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("file")]
        public string File { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _outerRadius = 5F;
        
        [System.ComponentModel.DefaultValueAttribute(5F)]
        [System.Xml.Serialization.XmlAttributeAttribute("outerRadius")]
        public float OuterRadius
        {
            get
            {
                return this._outerRadius;
            }
            set
            {
                this._outerRadius = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _innerRadius = 80F;
        
        [System.ComponentModel.DefaultValueAttribute(80F)]
        [System.Xml.Serialization.XmlAttributeAttribute("innerRadius")]
        public float InnerRadius
        {
            get
            {
                return this._innerRadius;
            }
            set
            {
                this._innerRadius = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _loops = "1";
        
        [System.ComponentModel.DefaultValueAttribute("1")]
        [System.Xml.Serialization.XmlAttributeAttribute("loops")]
        public string Loops
        {
            get
            {
                return this._loops;
            }
            set
            {
                this._loops = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _supportsReverb = "true";
        
        /// <summary>
        /// <para xml:lang="en">Pattern: true|false.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("true")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("true|false")]
        [System.Xml.Serialization.XmlAttributeAttribute("supportsReverb")]
        public string SupportsReverb
        {
            get
            {
                return this._supportsReverb;
            }
            set
            {
                this._supportsReverb = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _debug = "false";
        
        /// <summary>
        /// <para xml:lang="en">Pattern: true|false.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("false")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("true|false")]
        [System.Xml.Serialization.XmlAttributeAttribute("debug")]
        public string Debug
        {
            get
            {
                return this._debug;
            }
            set
            {
                this._debug = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _fadeIn = 0F;
        
        [System.ComponentModel.DefaultValueAttribute(0F)]
        [System.Xml.Serialization.XmlAttributeAttribute("fadeIn")]
        public float FadeIn
        {
            get
            {
                return this._fadeIn;
            }
            set
            {
                this._fadeIn = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _fadeOut = 0F;
        
        [System.ComponentModel.DefaultValueAttribute(0F)]
        [System.Xml.Serialization.XmlAttributeAttribute("fadeOut")]
        public float FadeOut
        {
            get
            {
                return this._fadeOut;
            }
            set
            {
                this._fadeOut = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _volumeScale = 1F;
        
        [System.ComponentModel.DefaultValueAttribute(1F)]
        [System.Xml.Serialization.XmlAttributeAttribute("volumeScale")]
        public float VolumeScale
        {
            get
            {
                return this._volumeScale;
            }
            set
            {
                this._volumeScale = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _pitchScale = 1F;
        
        [System.ComponentModel.DefaultValueAttribute(1F)]
        [System.Xml.Serialization.XmlAttributeAttribute("pitchScale")]
        public float PitchScale
        {
            get
            {
                return this._pitchScale;
            }
            set
            {
                this._pitchScale = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _lowpassGainScale = 1F;
        
        [System.ComponentModel.DefaultValueAttribute(1F)]
        [System.Xml.Serialization.XmlAttributeAttribute("lowpassGainScale")]
        public float LowpassGainScale
        {
            get
            {
                return this._lowpassGainScale;
            }
            set
            {
                this._lowpassGainScale = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SoundManager_SoundVolume", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoundManager_SoundVolume
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SoundManager_SoundVolumeModifier> _modifier;
        
        [System.Xml.Serialization.XmlElementAttribute("modifier", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<SoundManager_SoundVolumeModifier> Modifier
        {
            get
            {
                return this._modifier;
            }
            private set
            {
                this._modifier = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Modifier collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifierSpecified
        {
            get
            {
                return (this.Modifier.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SoundManager_SoundVolume" /> class.</para>
        /// </summary>
        public SoundManager_SoundVolume()
        {
            this._modifier = new System.Collections.ObjectModel.Collection<SoundManager_SoundVolumeModifier>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _indoor = 0.8F;
        
        [System.ComponentModel.DefaultValueAttribute(0.8F)]
        [System.Xml.Serialization.XmlAttributeAttribute("indoor")]
        public float Indoor
        {
            get
            {
                return this._indoor;
            }
            set
            {
                this._indoor = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _outdoor = 1F;
        
        [System.ComponentModel.DefaultValueAttribute(1F)]
        [System.Xml.Serialization.XmlAttributeAttribute("outdoor")]
        public float Outdoor
        {
            get
            {
                return this._outdoor;
            }
            set
            {
                this._outdoor = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SoundManager_SoundVolumeModifier", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoundManager_SoundVolumeModifier
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public float Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Value property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("modifiedValue")]
        public float ModifiedValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ModifiedValue property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifiedValueSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SoundManager_SoundPitch", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoundManager_SoundPitch
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SoundManager_SoundPitchModifier> _modifier;
        
        [System.Xml.Serialization.XmlElementAttribute("modifier", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<SoundManager_SoundPitchModifier> Modifier
        {
            get
            {
                return this._modifier;
            }
            private set
            {
                this._modifier = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Modifier collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifierSpecified
        {
            get
            {
                return (this.Modifier.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SoundManager_SoundPitch" /> class.</para>
        /// </summary>
        public SoundManager_SoundPitch()
        {
            this._modifier = new System.Collections.ObjectModel.Collection<SoundManager_SoundPitchModifier>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _indoor = 1F;
        
        [System.ComponentModel.DefaultValueAttribute(1F)]
        [System.Xml.Serialization.XmlAttributeAttribute("indoor")]
        public float Indoor
        {
            get
            {
                return this._indoor;
            }
            set
            {
                this._indoor = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _outdoor = 1F;
        
        [System.ComponentModel.DefaultValueAttribute(1F)]
        [System.Xml.Serialization.XmlAttributeAttribute("outdoor")]
        public float Outdoor
        {
            get
            {
                return this._outdoor;
            }
            set
            {
                this._outdoor = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SoundManager_SoundPitchModifier", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoundManager_SoundPitchModifier
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public float Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Value property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("modifiedValue")]
        public float ModifiedValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ModifiedValue property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifiedValueSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SoundManager_SoundLowpassGain", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoundManager_SoundLowpassGain
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SoundManager_SoundLowpassGainModifier> _modifier;
        
        [System.Xml.Serialization.XmlElementAttribute("modifier", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<SoundManager_SoundLowpassGainModifier> Modifier
        {
            get
            {
                return this._modifier;
            }
            private set
            {
                this._modifier = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Modifier collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifierSpecified
        {
            get
            {
                return (this.Modifier.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="SoundManager_SoundLowpassGain" /> class.</para>
        /// </summary>
        public SoundManager_SoundLowpassGain()
        {
            this._modifier = new System.Collections.ObjectModel.Collection<SoundManager_SoundLowpassGainModifier>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _indoor = 0.8F;
        
        [System.ComponentModel.DefaultValueAttribute(0.8F)]
        [System.Xml.Serialization.XmlAttributeAttribute("indoor")]
        public float Indoor
        {
            get
            {
                return this._indoor;
            }
            set
            {
                this._indoor = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _outdoor = 1F;
        
        [System.ComponentModel.DefaultValueAttribute(1F)]
        [System.Xml.Serialization.XmlAttributeAttribute("outdoor")]
        public float Outdoor
        {
            get
            {
                return this._outdoor;
            }
            set
            {
                this._outdoor = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SoundManager_SoundLowpassGainModifier", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoundManager_SoundLowpassGainModifier
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("type")]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public float Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Value property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("modifiedValue")]
        public float ModifiedValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ModifiedValue property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ModifiedValueSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SoundManager_SoundLowpassCutoffFrequency", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoundManager_SoundLowpassCutoffFrequency
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _indoor = 5000F;
        
        [System.ComponentModel.DefaultValueAttribute(5000F)]
        [System.Xml.Serialization.XmlAttributeAttribute("indoor")]
        public float Indoor
        {
            get
            {
                return this._indoor;
            }
            set
            {
                this._indoor = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _outdoor = 5000F;
        
        [System.ComponentModel.DefaultValueAttribute(5000F)]
        [System.Xml.Serialization.XmlAttributeAttribute("outdoor")]
        public float Outdoor
        {
            get
            {
                return this._outdoor;
            }
            set
            {
                this._outdoor = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SoundManager_SoundLowpassResonance", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoundManager_SoundLowpassResonance
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _indoor = 2F;
        
        [System.ComponentModel.DefaultValueAttribute(2F)]
        [System.Xml.Serialization.XmlAttributeAttribute("indoor")]
        public float Indoor
        {
            get
            {
                return this._indoor;
            }
            set
            {
                this._indoor = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private float _outdoor = 2F;
        
        [System.ComponentModel.DefaultValueAttribute(2F)]
        [System.Xml.Serialization.XmlAttributeAttribute("outdoor")]
        public float Outdoor
        {
            get
            {
                return this._outdoor;
            }
            set
            {
                this._outdoor = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SoundManager_SoundRandomization", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoundManager_SoundRandomization
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("minVolume")]
        public float MinVolume { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MinVolume property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinVolumeSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("maxVolume")]
        public float MaxVolume { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MaxVolume property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxVolumeSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("minPitch")]
        public float MinPitch { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MinPitch property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinPitchSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("maxPitch")]
        public float MaxPitch { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MaxPitch property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxPitchSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("minLowpassGain")]
        public float MinLowpassGain { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MinLowpassGain property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinLowpassGainSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("maxLowpassGain")]
        public float MaxLowpassGain { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MaxLowpassGain property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxLowpassGainSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _isInside = "true";
        
        /// <summary>
        /// <para xml:lang="en">Pattern: true|false.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("true")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("true|false")]
        [System.Xml.Serialization.XmlAttributeAttribute("isInside")]
        public string IsInside
        {
            get
            {
                return this._isInside;
            }
            set
            {
                this._isInside = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _isOutside = "true";
        
        /// <summary>
        /// <para xml:lang="en">Pattern: true|false.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("true")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("true|false")]
        [System.Xml.Serialization.XmlAttributeAttribute("isOutside")]
        public string IsOutside
        {
            get
            {
                return this._isOutside;
            }
            set
            {
                this._isOutside = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("SoundManager_SoundSourceRandomization", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SoundManager_SoundSourceRandomization
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("file")]
        public string File { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("map", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("map", Namespace="")]
    public partial class Map
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapFillTypesFillType> _fillTypes;
        
        [System.Xml.Serialization.XmlArrayAttribute("fillTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fillType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapFillTypesFillType> FillTypes
        {
            get
            {
                return this._fillTypes;
            }
            private set
            {
                this._fillTypes = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FillTypes collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FillTypesSpecified
        {
            get
            {
                return (this.FillTypes.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Map" /> class.</para>
        /// </summary>
        public Map()
        {
            this._fillTypes = new System.Collections.ObjectModel.Collection<MapFillTypesFillType>();
            this._fillTypeCategories = new System.Collections.ObjectModel.Collection<MapFillTypeCategoriesFillTypeCategory>();
            this._fillTypeConverters = new System.Collections.ObjectModel.Collection<MapFillTypeConvertersFillTypeConverter>();
            this._fillTypeSounds = new System.Collections.ObjectModel.Collection<MapFillTypeSoundsFillTypeSound>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("parentFile", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MapParentFile ParentFile { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapFillTypeCategoriesFillTypeCategory> _fillTypeCategories;
        
        [System.Xml.Serialization.XmlArrayAttribute("fillTypeCategories", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fillTypeCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapFillTypeCategoriesFillTypeCategory> FillTypeCategories
        {
            get
            {
                return this._fillTypeCategories;
            }
            private set
            {
                this._fillTypeCategories = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FillTypeCategories collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FillTypeCategoriesSpecified
        {
            get
            {
                return (this.FillTypeCategories.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapFillTypeConvertersFillTypeConverter> _fillTypeConverters;
        
        [System.Xml.Serialization.XmlArrayAttribute("fillTypeConverters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fillTypeConverter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapFillTypeConvertersFillTypeConverter> FillTypeConverters
        {
            get
            {
                return this._fillTypeConverters;
            }
            private set
            {
                this._fillTypeConverters = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FillTypeConverters collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FillTypeConvertersSpecified
        {
            get
            {
                return (this.FillTypeConverters.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapFillTypeSoundsFillTypeSound> _fillTypeSounds;
        
        [System.Xml.Serialization.XmlArrayAttribute("fillTypeSounds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("fillTypeSound", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapFillTypeSoundsFillTypeSound> FillTypeSounds
        {
            get
            {
                return this._fillTypeSounds;
            }
            private set
            {
                this._fillTypeSounds = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FillTypeSounds collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FillTypeSoundsSpecified
        {
            get
            {
                return (this.FillTypeSounds.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypes", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypes
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapFillTypesFillType> _fillType;
        
        [System.Xml.Serialization.XmlElementAttribute("fillType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapFillTypesFillType> FillType
        {
            get
            {
                return this._fillType;
            }
            private set
            {
                this._fillType = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FillType collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FillTypeSpecified
        {
            get
            {
                return (this.FillType.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapFillTypes" /> class.</para>
        /// </summary>
        public MapFillTypes()
        {
            this._fillType = new System.Collections.ObjectModel.Collection<MapFillTypesFillType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypesFillType", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypesFillType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("physics", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MapFillTypesFillTypePhysics Physics { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("image", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MapFillTypesFillTypeImage Image { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pallet", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MapFillTypesFillTypePallet Pallet { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("economy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MapFillTypesFillTypeEconomy Economy { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("textures", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MapFillTypesFillTypeTextures Textures { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("effects", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MapFillTypesFillTypeEffects Effects { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("title")]
        public string Title { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("achievementName")]
        public string AchievementName { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: true|false.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("true|false")]
        [System.Xml.Serialization.XmlAttributeAttribute("showOnPriceTable")]
        public string ShowOnPriceTable { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<string> _fillPlaneColors;
        
        /// <summary>
        /// <para xml:lang="en">Pattern: \S+ \S+ \S+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\S+ \\S+ \\S+")]
        [System.Xml.Serialization.XmlAttributeAttribute("fillPlaneColors")]
        public System.Collections.ObjectModel.Collection<string> FillPlaneColors
        {
            get
            {
                return this._fillPlaneColors;
            }
            private set
            {
                this._fillPlaneColors = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FillPlaneColors collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FillPlaneColorsSpecified
        {
            get
            {
                return (this.FillPlaneColors.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapFillTypesFillType" /> class.</para>
        /// </summary>
        public MapFillTypesFillType()
        {
            this._fillPlaneColors = new System.Collections.ObjectModel.Collection<string>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("unitShort")]
        public string UnitShort { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypesFillTypePhysics", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypesFillTypePhysics
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("massPerLiter")]
        public float MassPerLiter { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MassPerLiter property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MassPerLiterSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("maxPhysicalSurfaceAngle")]
        public float MaxPhysicalSurfaceAngle { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MaxPhysicalSurfaceAngle property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MaxPhysicalSurfaceAngleSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypesFillTypeImage", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypesFillTypeImage
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("hud")]
        public string Hud { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypesFillTypePallet", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypesFillTypePallet
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("filename")]
        public string Filename { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypesFillTypeEconomy", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypesFillTypeEconomy
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapFillTypesFillTypeEconomyFactorsFactor> _factors;
        
        [System.Xml.Serialization.XmlArrayAttribute("factors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("factor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapFillTypesFillTypeEconomyFactorsFactor> Factors
        {
            get
            {
                return this._factors;
            }
            private set
            {
                this._factors = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Factors collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FactorsSpecified
        {
            get
            {
                return (this.Factors.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapFillTypesFillTypeEconomy" /> class.</para>
        /// </summary>
        public MapFillTypesFillTypeEconomy()
        {
            this._factors = new System.Collections.ObjectModel.Collection<MapFillTypesFillTypeEconomyFactorsFactor>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("pricePerLiter")]
        public float PricePerLiter { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PricePerLiter property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PricePerLiterSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypesFillTypeEconomyFactors", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypesFillTypeEconomyFactors
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapFillTypesFillTypeEconomyFactorsFactor> _factor;
        
        [System.Xml.Serialization.XmlElementAttribute("factor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapFillTypesFillTypeEconomyFactorsFactor> Factor
        {
            get
            {
                return this._factor;
            }
            private set
            {
                this._factor = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Factor collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FactorSpecified
        {
            get
            {
                return (this.Factor.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapFillTypesFillTypeEconomyFactors" /> class.</para>
        /// </summary>
        public MapFillTypesFillTypeEconomyFactors()
        {
            this._factor = new System.Collections.ObjectModel.Collection<MapFillTypesFillTypeEconomyFactorsFactor>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypesFillTypeEconomyFactorsFactor", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypesFillTypeEconomyFactorsFactor
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("period")]
        public string Period { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public float Value { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Value property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypesFillTypeTextures", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypesFillTypeTextures
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("diffuse")]
        public string Diffuse { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("normal")]
        public string Normal { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("specular")]
        public string Specular { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("distance")]
        public string Distance { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypesFillTypeEffects", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypesFillTypeEffects
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _prioritizedEffectType = "ShaderPlaneEffect";
        
        [System.ComponentModel.DefaultValueAttribute("ShaderPlaneEffect")]
        [System.Xml.Serialization.XmlAttributeAttribute("prioritizedEffectType")]
        public string PrioritizedEffectType
        {
            get
            {
                return this._prioritizedEffectType;
            }
            set
            {
                this._prioritizedEffectType = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: \S+ \S+ \S+ \S+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\S+ \\S+ \\S+ \\S+")]
        [System.Xml.Serialization.XmlAttributeAttribute("fillSmokeColor")]
        public System.Collections.ObjectModel.Collection<string> FillSmokeColor { get; private set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FillSmokeColor collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FillSmokeColorSpecified
        {
            get
            {
                return (this.FillSmokeColor.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapFillTypesFillTypeEffects" /> class.</para>
        /// </summary>
        public MapFillTypesFillTypeEffects()
        {
            this.FillSmokeColor = new System.Collections.ObjectModel.Collection<string>();
            this.FruitSmokeColor = new System.Collections.ObjectModel.Collection<string>();
        }
        
        /// <summary>
        /// <para xml:lang="en">Pattern: \S+ \S+ \S+ \S+.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("\\S+ \\S+ \\S+ \\S+")]
        [System.Xml.Serialization.XmlAttributeAttribute("fruitSmokeColor")]
        public System.Collections.ObjectModel.Collection<string> FruitSmokeColor { get; private set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FruitSmokeColor collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FruitSmokeColorSpecified
        {
            get
            {
                return (this.FruitSmokeColor.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapParentFile", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapParentFile
    {
        
        [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public MapParentFileAttributes Attributes { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("xmlFilename")]
        public string XmlFilename { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapParentFileAttributes", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapParentFileAttributes
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapParentFileAttributesRemove> _remove;
        
        [System.Xml.Serialization.XmlElementAttribute("remove", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapParentFileAttributesRemove> Remove
        {
            get
            {
                return this._remove;
            }
            private set
            {
                this._remove = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Remove collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RemoveSpecified
        {
            get
            {
                return (this.Remove.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapParentFileAttributes" /> class.</para>
        /// </summary>
        public MapParentFileAttributes()
        {
            this._remove = new System.Collections.ObjectModel.Collection<MapParentFileAttributesRemove>();
            this._set = new System.Collections.ObjectModel.Collection<MapParentFileAttributesSet>();
            this._clearList = new System.Collections.ObjectModel.Collection<MapParentFileAttributesClearList>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapParentFileAttributesSet> _set;
        
        [System.Xml.Serialization.XmlElementAttribute("set", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapParentFileAttributesSet> Set
        {
            get
            {
                return this._set;
            }
            private set
            {
                this._set = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Set collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SetSpecified
        {
            get
            {
                return (this.Set.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapParentFileAttributesClearList> _clearList;
        
        [System.Xml.Serialization.XmlElementAttribute("clearList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapParentFileAttributesClearList> ClearList
        {
            get
            {
                return this._clearList;
            }
            private set
            {
                this._clearList = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ClearList collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ClearListSpecified
        {
            get
            {
                return (this.ClearList.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapParentFileAttributesRemove", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapParentFileAttributesRemove
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("path")]
        public string Path { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapParentFileAttributesSet", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapParentFileAttributesSet
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("path")]
        public string Path { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("value")]
        public string Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapParentFileAttributesClearList", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapParentFileAttributesClearList
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("path")]
        public string Path { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("keepIndex")]
        public string KeepIndex { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypeCategories", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypeCategories
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapFillTypeCategoriesFillTypeCategory> _fillTypeCategory;
        
        [System.Xml.Serialization.XmlElementAttribute("fillTypeCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapFillTypeCategoriesFillTypeCategory> FillTypeCategory
        {
            get
            {
                return this._fillTypeCategory;
            }
            private set
            {
                this._fillTypeCategory = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FillTypeCategory collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FillTypeCategorySpecified
        {
            get
            {
                return (this.FillTypeCategory.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapFillTypeCategories" /> class.</para>
        /// </summary>
        public MapFillTypeCategories()
        {
            this._fillTypeCategory = new System.Collections.ObjectModel.Collection<MapFillTypeCategoriesFillTypeCategory>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypeCategoriesFillTypeCategory", Namespace="")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypeCategoriesFillTypeCategory
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypeConverters", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypeConverters
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapFillTypeConvertersFillTypeConverter> _fillTypeConverter;
        
        [System.Xml.Serialization.XmlElementAttribute("fillTypeConverter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapFillTypeConvertersFillTypeConverter> FillTypeConverter
        {
            get
            {
                return this._fillTypeConverter;
            }
            private set
            {
                this._fillTypeConverter = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FillTypeConverter collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FillTypeConverterSpecified
        {
            get
            {
                return (this.FillTypeConverter.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapFillTypeConverters" /> class.</para>
        /// </summary>
        public MapFillTypeConverters()
        {
            this._fillTypeConverter = new System.Collections.ObjectModel.Collection<MapFillTypeConvertersFillTypeConverter>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypeConvertersFillTypeConverter", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypeConvertersFillTypeConverter
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapFillTypeConvertersFillTypeConverterConverter> _converter;
        
        [System.Xml.Serialization.XmlElementAttribute("converter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapFillTypeConvertersFillTypeConverterConverter> Converter
        {
            get
            {
                return this._converter;
            }
            private set
            {
                this._converter = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Converter collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConverterSpecified
        {
            get
            {
                return (this.Converter.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapFillTypeConvertersFillTypeConverter" /> class.</para>
        /// </summary>
        public MapFillTypeConvertersFillTypeConverter()
        {
            this._converter = new System.Collections.ObjectModel.Collection<MapFillTypeConvertersFillTypeConverterConverter>();
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypeConvertersFillTypeConverterConverter", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypeConvertersFillTypeConverterConverter
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("from")]
        public string From { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("to")]
        public string To { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("factor")]
        public float Factor { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Factor property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FactorSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypeSounds", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypeSounds
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<MapFillTypeSoundsFillTypeSound> _fillTypeSound;
        
        [System.Xml.Serialization.XmlElementAttribute("fillTypeSound", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<MapFillTypeSoundsFillTypeSound> FillTypeSound
        {
            get
            {
                return this._fillTypeSound;
            }
            private set
            {
                this._fillTypeSound = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the FillTypeSound collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FillTypeSoundSpecified
        {
            get
            {
                return (this.FillTypeSound.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="MapFillTypeSounds" /> class.</para>
        /// </summary>
        public MapFillTypeSounds()
        {
            this._fillTypeSound = new System.Collections.ObjectModel.Collection<MapFillTypeSoundsFillTypeSound>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.629.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MapFillTypeSoundsFillTypeSound", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MapFillTypeSoundsFillTypeSound
    {
        
        [System.Xml.Serialization.XmlElementAttribute("sound", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoundManager_Sound Sound { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("fillTypes")]
        public string FillTypes { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _isDefault = "false";
        
        /// <summary>
        /// <para xml:lang="en">Pattern: true|false.</para>
        /// </summary>
        [System.ComponentModel.DefaultValueAttribute("false")]
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute("true|false")]
        [System.Xml.Serialization.XmlAttributeAttribute("isDefault")]
        public string IsDefault
        {
            get
            {
                return this._isDefault;
            }
            set
            {
                this._isDefault = value;
            }
        }
    }
}
